version: "3.9"
services:
  litefs-primary:
    image: litefs-client:latest
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./litefs-primary.yml:/etc/litefs.yml:ro
    command: "litefs mount"
  litefs-replica:
    image: litefs-client:latest
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./litefs-replica.yml:/etc/litefs.yml:ro
    command: "litefs mount"
